/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carlosmo
 */
public class Cuadro extends javax.swing.JFrame {

    /**
     * Creates new form Cuadro
     */
    public Cuadro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWest = new javax.swing.JPanel();
        pnlSouth = new javax.swing.JPanel();
        pnlNorth = new javax.swing.JPanel();
        pnlDerecha = new javax.swing.JPanel();
        pnlVerdeDerecha = new javax.swing.JPanel();
        pnlAzulDerecha = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        pnlNorth2 = new javax.swing.JPanel();
        pnlOscuroNorteCentro = new javax.swing.JPanel();
        pnlNegroNorteCentro = new javax.swing.JPanel();
        pnlAzulNorteCentro = new javax.swing.JPanel();
        pnlWest2 = new javax.swing.JPanel();
        pnlCentro2 = new javax.swing.JPanel();
        pnlNorth3 = new javax.swing.JPanel();
        pnelSouth3 = new javax.swing.JPanel();
        pnlCentro3 = new javax.swing.JPanel();
        pnlNorth4 = new javax.swing.JPanel();
        pnlSouth4 = new javax.swing.JPanel();
        pnlCentro4 = new javax.swing.JPanel();
        pnlCentro5 = new javax.swing.JPanel();
        pnlWest5 = new javax.swing.JPanel();
        pnlEast5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlWest.setBackground(new java.awt.Color(255, 255, 0));
        pnlWest.setPreferredSize(new java.awt.Dimension(80, 100));

        javax.swing.GroupLayout pnlWestLayout = new javax.swing.GroupLayout(pnlWest);
        pnlWest.setLayout(pnlWestLayout);
        pnlWestLayout.setHorizontalGroup(
            pnlWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pnlWestLayout.setVerticalGroup(
            pnlWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pnlWest, java.awt.BorderLayout.WEST);

        pnlSouth.setBackground(new java.awt.Color(0, 51, 255));
        pnlSouth.setPreferredSize(new java.awt.Dimension(600, 40));

        javax.swing.GroupLayout pnlSouthLayout = new javax.swing.GroupLayout(pnlSouth);
        pnlSouth.setLayout(pnlSouthLayout);
        pnlSouthLayout.setHorizontalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        pnlSouthLayout.setVerticalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(pnlSouth, java.awt.BorderLayout.SOUTH);

        pnlNorth.setBackground(new java.awt.Color(255, 0, 0));
        pnlNorth.setPreferredSize(new java.awt.Dimension(600, 40));

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(pnlNorth, java.awt.BorderLayout.NORTH);

        pnlDerecha.setPreferredSize(new java.awt.Dimension(80, 100));
        pnlDerecha.setLayout(new java.awt.BorderLayout());

        pnlVerdeDerecha.setBackground(new java.awt.Color(204, 255, 204));
        pnlVerdeDerecha.setPreferredSize(new java.awt.Dimension(80, 70));

        javax.swing.GroupLayout pnlVerdeDerechaLayout = new javax.swing.GroupLayout(pnlVerdeDerecha);
        pnlVerdeDerecha.setLayout(pnlVerdeDerechaLayout);
        pnlVerdeDerechaLayout.setHorizontalGroup(
            pnlVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pnlVerdeDerechaLayout.setVerticalGroup(
            pnlVerdeDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlDerecha.add(pnlVerdeDerecha, java.awt.BorderLayout.SOUTH);

        pnlAzulDerecha.setBackground(new java.awt.Color(0, 51, 255));
        pnlAzulDerecha.setPreferredSize(new java.awt.Dimension(90, 120));

        javax.swing.GroupLayout pnlAzulDerechaLayout = new javax.swing.GroupLayout(pnlAzulDerecha);
        pnlAzulDerecha.setLayout(pnlAzulDerechaLayout);
        pnlAzulDerechaLayout.setHorizontalGroup(
            pnlAzulDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pnlAzulDerechaLayout.setVerticalGroup(
            pnlAzulDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        pnlDerecha.add(pnlAzulDerecha, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDerecha, java.awt.BorderLayout.EAST);

        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlNorth2.setPreferredSize(new java.awt.Dimension(440, 20));
        pnlNorth2.setLayout(new java.awt.BorderLayout());

        pnlOscuroNorteCentro.setBackground(new java.awt.Color(0, 102, 102));
        pnlOscuroNorteCentro.setPreferredSize(new java.awt.Dimension(20, 100));

        javax.swing.GroupLayout pnlOscuroNorteCentroLayout = new javax.swing.GroupLayout(pnlOscuroNorteCentro);
        pnlOscuroNorteCentro.setLayout(pnlOscuroNorteCentroLayout);
        pnlOscuroNorteCentroLayout.setHorizontalGroup(
            pnlOscuroNorteCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnlOscuroNorteCentroLayout.setVerticalGroup(
            pnlOscuroNorteCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlNorth2.add(pnlOscuroNorteCentro, java.awt.BorderLayout.EAST);

        pnlNegroNorteCentro.setBackground(new java.awt.Color(0, 0, 0));
        pnlNegroNorteCentro.setPreferredSize(new java.awt.Dimension(20, 100));

        javax.swing.GroupLayout pnlNegroNorteCentroLayout = new javax.swing.GroupLayout(pnlNegroNorteCentro);
        pnlNegroNorteCentro.setLayout(pnlNegroNorteCentroLayout);
        pnlNegroNorteCentroLayout.setHorizontalGroup(
            pnlNegroNorteCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        pnlNegroNorteCentroLayout.setVerticalGroup(
            pnlNegroNorteCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlNorth2.add(pnlNegroNorteCentro, java.awt.BorderLayout.CENTER);

        pnlAzulNorteCentro.setBackground(new java.awt.Color(102, 204, 255));
        pnlAzulNorteCentro.setMinimumSize(new java.awt.Dimension(20, 100));
        pnlAzulNorteCentro.setPreferredSize(new java.awt.Dimension(20, 0));

        javax.swing.GroupLayout pnlAzulNorteCentroLayout = new javax.swing.GroupLayout(pnlAzulNorteCentro);
        pnlAzulNorteCentro.setLayout(pnlAzulNorteCentroLayout);
        pnlAzulNorteCentroLayout.setHorizontalGroup(
            pnlAzulNorteCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnlAzulNorteCentroLayout.setVerticalGroup(
            pnlAzulNorteCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlNorth2.add(pnlAzulNorteCentro, java.awt.BorderLayout.WEST);

        pnlCenter.add(pnlNorth2, java.awt.BorderLayout.NORTH);

        pnlWest2.setBackground(new java.awt.Color(204, 204, 0));
        pnlWest2.setPreferredSize(new java.awt.Dimension(120, 100));

        javax.swing.GroupLayout pnlWest2Layout = new javax.swing.GroupLayout(pnlWest2);
        pnlWest2.setLayout(pnlWest2Layout);
        pnlWest2Layout.setHorizontalGroup(
            pnlWest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        pnlWest2Layout.setVerticalGroup(
            pnlWest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlWest2, java.awt.BorderLayout.WEST);

        pnlCentro2.setLayout(new java.awt.BorderLayout());

        pnlNorth3.setBackground(new java.awt.Color(153, 0, 0));
        pnlNorth3.setPreferredSize(new java.awt.Dimension(20, 40));

        javax.swing.GroupLayout pnlNorth3Layout = new javax.swing.GroupLayout(pnlNorth3);
        pnlNorth3.setLayout(pnlNorth3Layout);
        pnlNorth3Layout.setHorizontalGroup(
            pnlNorth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        pnlNorth3Layout.setVerticalGroup(
            pnlNorth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCentro2.add(pnlNorth3, java.awt.BorderLayout.NORTH);

        pnelSouth3.setBackground(new java.awt.Color(51, 255, 153));
        pnelSouth3.setPreferredSize(new java.awt.Dimension(20, 40));

        javax.swing.GroupLayout pnelSouth3Layout = new javax.swing.GroupLayout(pnelSouth3);
        pnelSouth3.setLayout(pnelSouth3Layout);
        pnelSouth3Layout.setHorizontalGroup(
            pnelSouth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        pnelSouth3Layout.setVerticalGroup(
            pnelSouth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlCentro2.add(pnelSouth3, java.awt.BorderLayout.SOUTH);

        pnlCentro3.setLayout(new java.awt.BorderLayout());

        pnlNorth4.setBackground(new java.awt.Color(204, 255, 0));
        pnlNorth4.setPreferredSize(new java.awt.Dimension(320, 50));

        javax.swing.GroupLayout pnlNorth4Layout = new javax.swing.GroupLayout(pnlNorth4);
        pnlNorth4.setLayout(pnlNorth4Layout);
        pnlNorth4Layout.setHorizontalGroup(
            pnlNorth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        pnlNorth4Layout.setVerticalGroup(
            pnlNorth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlCentro3.add(pnlNorth4, java.awt.BorderLayout.NORTH);

        pnlSouth4.setBackground(new java.awt.Color(153, 153, 255));
        pnlSouth4.setPreferredSize(new java.awt.Dimension(320, 50));

        javax.swing.GroupLayout pnlSouth4Layout = new javax.swing.GroupLayout(pnlSouth4);
        pnlSouth4.setLayout(pnlSouth4Layout);
        pnlSouth4Layout.setHorizontalGroup(
            pnlSouth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        pnlSouth4Layout.setVerticalGroup(
            pnlSouth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlCentro3.add(pnlSouth4, java.awt.BorderLayout.SOUTH);

        pnlCentro4.setPreferredSize(new java.awt.Dimension(320, 40));
        pnlCentro4.setLayout(new java.awt.BorderLayout());

        pnlCentro5.setBackground(new java.awt.Color(255, 0, 0));
        pnlCentro5.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout pnlCentro5Layout = new javax.swing.GroupLayout(pnlCentro5);
        pnlCentro5.setLayout(pnlCentro5Layout);
        pnlCentro5Layout.setHorizontalGroup(
            pnlCentro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        pnlCentro5Layout.setVerticalGroup(
            pnlCentro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCentro4.add(pnlCentro5, java.awt.BorderLayout.CENTER);

        pnlWest5.setBackground(new java.awt.Color(204, 204, 255));
        pnlWest5.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout pnlWest5Layout = new javax.swing.GroupLayout(pnlWest5);
        pnlWest5.setLayout(pnlWest5Layout);
        pnlWest5Layout.setHorizontalGroup(
            pnlWest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlWest5Layout.setVerticalGroup(
            pnlWest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCentro4.add(pnlWest5, java.awt.BorderLayout.WEST);

        pnlEast5.setPreferredSize(new java.awt.Dimension(50, 30));

        javax.swing.GroupLayout pnlEast5Layout = new javax.swing.GroupLayout(pnlEast5);
        pnlEast5.setLayout(pnlEast5Layout);
        pnlEast5Layout.setHorizontalGroup(
            pnlEast5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlEast5Layout.setVerticalGroup(
            pnlEast5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlCentro4.add(pnlEast5, java.awt.BorderLayout.EAST);

        pnlCentro3.add(pnlCentro4, java.awt.BorderLayout.CENTER);

        pnlCentro2.add(pnlCentro3, java.awt.BorderLayout.CENTER);

        pnlCenter.add(pnlCentro2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuadro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuadro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnelSouth3;
    private javax.swing.JPanel pnlAzulDerecha;
    private javax.swing.JPanel pnlAzulNorteCentro;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlCentro2;
    private javax.swing.JPanel pnlCentro3;
    private javax.swing.JPanel pnlCentro4;
    private javax.swing.JPanel pnlCentro5;
    private javax.swing.JPanel pnlDerecha;
    private javax.swing.JPanel pnlEast5;
    private javax.swing.JPanel pnlNegroNorteCentro;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnlNorth2;
    private javax.swing.JPanel pnlNorth3;
    private javax.swing.JPanel pnlNorth4;
    private javax.swing.JPanel pnlOscuroNorteCentro;
    private javax.swing.JPanel pnlSouth;
    private javax.swing.JPanel pnlSouth4;
    private javax.swing.JPanel pnlVerdeDerecha;
    private javax.swing.JPanel pnlWest;
    private javax.swing.JPanel pnlWest2;
    private javax.swing.JPanel pnlWest5;
    // End of variables declaration//GEN-END:variables
}
