
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carlos Maroño Ovies
 */
public class Formulario extends javax.swing.JFrame {
    private DefaultTreeModel model;
    private DefaultTableModel modelTabla;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        model = (DefaultTreeModel) TreeCuadrillas.getModel();
        modelTabla = (DefaultTableModel) tableEmpleados.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabla = new javax.swing.JScrollPane();
        tableEmpleados = new javax.swing.JTable();
        txtLocalidad = new javax.swing.JTextField();
        buttonAltaLocalidad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        buttonAltaEmpleado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboLocalidades = new javax.swing.JComboBox<>();
        buttonTrabajadores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreeCuadrillas = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Localidad");

        tableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cargo"
            }
        ));
        tabla.setViewportView(tableEmpleados);

        buttonAltaLocalidad.setText("Alta Localidad");
        buttonAltaLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltaLocalidadActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Nuevo empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        buttonAltaEmpleado.setText("Alta");
        buttonAltaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltaEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido)))
                .addGap(18, 18, 18)
                .addComponent(buttonAltaEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAltaEmpleado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Localidades");

        buttonTrabajadores.setText("Trabajadores");
        buttonTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrabajadoresActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("CUADRILLAS");
        TreeCuadrillas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(TreeCuadrillas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(buttonAltaLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAltaLocalidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTrabajadores))
                        .addGap(28, 28, 28)
                        .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAltaLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltaLocalidadActionPerformed
        // TODO add your handling code here:
      String nombreLocalidad = txtLocalidad.getText();
      
      if(nombreLocalidad.isBlank()){
          JOptionPane.showMessageDialog(this,"Error: Debe de rellenar el campo nombre para añadir una locaidad");
          return;
      }
      //Creamos la nueva localidad
      Localidad nuevaLocalidad = new Localidad(nombreLocalidad);
      //Creamos un nodo para la nueva localidad
      DefaultMutableTreeNode nodoNuevaLocalidad = new DefaultMutableTreeNode(nuevaLocalidad);
      //COgemos el nodo raiz para añadirle el nuevo nodo
      DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
      //Añadimos el nuevo nodo 
      model.insertNodeInto(nodoNuevaLocalidad, root, root.getChildCount());
      //Recargamos el modelo
      model.reload();
      //Añadimos la localidad al comboBox de localidades
      comboLocalidades.addItem(nombreLocalidad);
      txtLocalidad.setText("");
    }//GEN-LAST:event_buttonAltaLocalidadActionPerformed

    private void buttonAltaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltaEmpleadoActionPerformed
        // TODO add your handling code here:
        
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) TreeCuadrillas.getLastSelectedPathComponent();
        
        if(nodoSeleccionado == null){
            JOptionPane.showMessageDialog(this,"Error: Debe seleccionar un nodo");
            return;
        }
        
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        
        if(nombre.isBlank() || apellido.isBlank()){
            JOptionPane.showMessageDialog(this,"Error: los campos Nombre y Apellido son obligatorios");
            return;
        }
            
        Object objetoNodo = nodoSeleccionado.getUserObject();
        
        String cargo="";
        if(objetoNodo instanceof  Localidad){
            cargo="JEFE";
            
             if(nodoSeleccionado.getChildCount()> 0){
            JOptionPane.showMessageDialog(this,"Error:Esta localidad ya tiene un jefe");
            return;
        }
             
        }else if(objetoNodo instanceof Empleado){
            Empleado empleadoSeleccionado = (Empleado) objetoNodo;
            
            if(empleadoSeleccionado.getCargo().equals("JEFE")){
                cargo="1ER OFICIAL";
            }else if (empleadoSeleccionado.getCargo().equals("1ER OFICIAL")){
                cargo = "2º OFICIAL";
            }else{
                JOptionPane.showMessageDialog(this,"Error:No se puede añadir un empleado a un 2º OFICIAL");
                return;
            }
        }else{
            JOptionPane.showMessageDialog(this,"No se puede añadir un empleado a este nodo");
            return;
        }
        //Si todo va bien cremaos el empleado
        
        Empleado nuevoEmpleado = new Empleado(nombre, apellido, cargo);
        //Creamos un nodo con el empleado nuevo
        DefaultMutableTreeNode nodoNuevoEmpleado = new DefaultMutableTreeNode(nuevoEmpleado);
        //Añadimos el nodo nuevo
        model.insertNodeInto(nodoNuevoEmpleado, nodoSeleccionado, nodoSeleccionado.getChildCount());
        //Refrescamos el modelo
        model.reload();
        
        txtNombre.setText("");
        txtApellido.setText("");
        
        
       
        
    }//GEN-LAST:event_buttonAltaEmpleadoActionPerformed

    private void buttonTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrabajadoresActionPerformed
        // TODO add your handling code here:
     String localidadSeleccionada = (String) comboLocalidades.getSelectedItem();
     
     if(localidadSeleccionada == null){
         JOptionPane.showMessageDialog(this,"Error: No hay ninguna localidad seleccionada");
         return;
     }
     //Limpiar la tabla
     modelTabla.setRowCount(0);
     //Hay que buscar el nodo de esa localidad para coger los empleados
     DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
     DefaultMutableTreeNode localidadEncontrada = null;
     
     for(int i =0;i<root.getChildCount();i++){
         DefaultMutableTreeNode nodoActual = (DefaultMutableTreeNode) root.getChildAt(i);
         
         if(nodoActual.getUserObject() instanceof Localidad){
             Localidad localidad = (Localidad) nodoActual.getUserObject();
             
             if(localidad.getNombre().equals(localidadSeleccionada)){
                 localidadEncontrada= nodoActual;
                 break;
             }
         }
     }
     //Una vez encontrado toca recorrer y rellenar la tabla
     if(localidadEncontrada !=null){
         
         if(localidadEncontrada.getChildCount() > 0){
             
             DefaultMutableTreeNode nodoJefe = (DefaultMutableTreeNode) localidadEncontrada.getChildAt(0);
             
             Empleado jefe = (Empleado) nodoJefe.getUserObject();
             
             modelTabla.addRow(new Object[]{
                 jefe.getNombre(),
                 jefe.getApellido(),
                 jefe.getCargo()});
             for(int i =0;i < nodoJefe.getChildCount();i++){
                 
                 DefaultMutableTreeNode nodoOficialDe1 = (DefaultMutableTreeNode) nodoJefe.getChildAt(i);
                 
                 Empleado oficial1 = (Empleado) nodoOficialDe1.getUserObject();
                 
                 modelTabla.addRow(new Object[]{
                 oficial1.getNombre(),
                     oficial1.getApellido(),
                     oficial1.getCargo()
                 });
                 
                 for(int j =0; j < nodoOficialDe1.getChildCount();j++){
                     DefaultMutableTreeNode nodoOficial2 = (DefaultMutableTreeNode) nodoOficialDe1.getChildAt(j);
                     
                     Empleado oficial2 = (Empleado) nodoOficial2.getUserObject();
                     
                     modelTabla.addRow(new Object[]{
                     oficial2.getNombre(),
                         oficial2.getApellido(),
                         oficial2.getCargo()
                     });
                 }
             }
         }
         
        
     }
     
    }//GEN-LAST:event_buttonTrabajadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree TreeCuadrillas;
    private javax.swing.JButton buttonAltaEmpleado;
    private javax.swing.JButton buttonAltaLocalidad;
    private javax.swing.JButton buttonTrabajadores;
    private javax.swing.JComboBox<String> comboLocalidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane tabla;
    private javax.swing.JTable tableEmpleados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
