
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carlosmo
 */
public class Registro extends javax.swing.JFrame {
    DefaultComboBoxModel<String> modeloProvicnia;
    DefaultListModel<String> modelosProfesion;
    DefaultTableModel modeloTabla;
    List<Traballador> listaTraballadores;
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        //Inicializamos los atributos
        this.modeloProvicnia = new DefaultComboBoxModel<>();
        this.modelosProfesion = new DefaultListModel<>();

         this.modeloTabla =  (DefaultTableModel) tableTrabajadores.getModel();
         modeloTabla.setRowCount(0);
          this.listaTraballadores = new ArrayList<>();
          
          
        //Usamos los atributos para hacer los modelos de las listas,tablas etc
        comboProvincia.setModel(modeloProvicnia);
        listProfesion.setModel(modelosProfesion);
       
        
      
        
        List<String> provincias = new ArrayList<>();
        provincias.add("A Coruña");
        provincias.add("Lugo");
        provincias.add("Pontevedra");
        provincias.add("Ourense");
        modeloProvicnia.addAll(provincias);
        
        List<String> profesiones = new ArrayList<>();
        profesiones.add("Carpinteiro");
        profesiones.add("Fontaneiro");
        profesiones.add("Electricista");
        profesiones.add("Soldador");
        modelosProfesion.addAll(profesiones);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtApelido1 = new javax.swing.JTextField();
        txtApelido2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        comboProvincia = new javax.swing.JComboBox<>();
        txtProvincia = new javax.swing.JTextField();
        buttonEliminarProvincia = new javax.swing.JButton();
        buttonEngadirProvincia = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProfesion = new javax.swing.JList<>();
        buttonEliminarProfesion = new javax.swing.JButton();
        txtProfesion = new javax.swing.JTextField();
        buttonEngadirProfesion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTrabajadores = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTraballador = new javax.swing.JTextArea();
        buttonPecharAplicaicon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compoñentes avanzados");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Identificacion do traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("DNI");

        jLabel2.setText("Nome");

        jLabel3.setText("Apelido 1");

        jLabel4.setText("Apelido 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtApelido1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtApelido2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDni)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtApelido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtApelido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Provincia do traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonEliminarProvincia.setText("Eliminar provincia");
        buttonEliminarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarProvinciaActionPerformed(evt);
            }
        });

        buttonEngadirProvincia.setText("Engadir provincia");
        buttonEngadirProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEngadirProvinciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboProvincia, 0, 173, Short.MAX_VALUE)
                    .addComponent(txtProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEliminarProvincia)
                    .addComponent(buttonEngadirProvincia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEliminarProvincia))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEngadirProvincia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Profesions do traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        listProfesion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listProfesion);

        buttonEliminarProfesion.setText("Eliminar profesion");
        buttonEliminarProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarProfesionActionPerformed(evt);
            }
        });

        buttonEngadirProfesion.setText("Engadir profesion");
        buttonEngadirProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEngadirProfesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEliminarProfesion)
                    .addComponent(buttonEngadirProfesion)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEliminarProfesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEngadirProfesion))
                .addGap(5, 5, 5))
        );

        jButton1.setText("Engadir traballador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Traballadores dispoñibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tableTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome e apelidos", "Provincia", "Profesion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTrabajadoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableTrabajadores);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setText("Eliminar traballador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Detalle do traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtAreaTraballador.setEditable(false);
        txtAreaTraballador.setColumns(20);
        txtAreaTraballador.setRows(5);
        jScrollPane2.setViewportView(txtAreaTraballador);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        buttonPecharAplicaicon.setText("Pechar aplicacion");
        buttonPecharAplicaicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPecharAplicaiconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(buttonPecharAplicaicon, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(buttonPecharAplicaicon)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarProvinciaActionPerformed
        // TODO add your handling code here:
        Object seleccionada = comboProvincia.getSelectedItem();
        
        String provincia = (String) seleccionada;
        
        if(modeloProvicnia.getSize() == 0 ){
            JOptionPane.showMessageDialog(this,"A lista esta valeira");
            return;
        }        
        if(seleccionada !=null ){
             modeloProvicnia.removeElement(seleccionada);
            
        }else{
            JOptionPane.showMessageDialog(this,"Selecciona unha provincia");
        }
        
    }//GEN-LAST:event_buttonEliminarProvinciaActionPerformed

    private void buttonEngadirProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEngadirProvinciaActionPerformed
        // TODO add your handling code here:
        
        if(!txtProvincia.getText().isBlank()){
            
            modeloProvicnia.addElement(txtProvincia.getText());
            
            txtProvincia.setText("");
        }else{
            JOptionPane.showMessageDialog(this,"Debe escribir unha provincia");
        }
    }//GEN-LAST:event_buttonEngadirProvinciaActionPerformed

    private void buttonEliminarProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarProfesionActionPerformed
        // TODO add your handling code here:
        
        if(modelosProfesion.isEmpty()){
            JOptionPane.showMessageDialog(this,"A lista de profesions esta valeira");
            return;
        }
        if(listProfesion.getSelectedValue()!=null){
            
            modelosProfesion.removeElement(listProfesion.getSelectedValue());
            
        }else{
            JOptionPane.showMessageDialog(this,"Seleccione unha profesion");
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_buttonEliminarProfesionActionPerformed

    private void buttonEngadirProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEngadirProfesionActionPerformed
        // TODO add your handling code here:
        
        if(!txtProfesion.getText().isBlank()){
            
            modelosProfesion.addElement(txtProfesion.getText());
           
            txtProfesion.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Escriba unha profesion ");
        }
    }//GEN-LAST:event_buttonEngadirProfesionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Comprobamos que los campos estan cubiertos
        if(txtDni.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Escriba o DNI");
        }else if(txtNome.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Escriba o Nome");
        }else if(txtApelido1.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Escriba o Apelido 1");
        }else if(txtApelido2.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Escriba o Apelido 2");
        }else if(comboProvincia.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this,"Escolla unha Provincia");
        }else if(listProfesion.getSelectedValue() == null){
            JOptionPane.showMessageDialog(this,"Escolla unha Profesion");
        }else{
            
            for(Traballador t : listaTraballadores){
                
                if(t.getDni().equals(txtDni.getText())){
                    JOptionPane.showMessageDialog(this,"Existe un traballador con ese DNI");
                    txtDni.setText("");
                    return;
                    
                }
            }    
            
            String provincia = (String) comboProvincia.getSelectedItem();
            String profesion = listProfesion.getSelectedValue();
            Traballador novo = new Traballador(txtDni.getText(), txtNome.getText(), txtApelido1.getText(), txtApelido2.getText(), provincia, profesion);
            
            listaTraballadores.add(novo);
            
            Object[] filaParaTabla = new Object[3];
            filaParaTabla[0] = novo.getNome() + " "+ novo.getApelido1() + " "+ novo.getApelido2();
            filaParaTabla[1] = novo.getProvincia();
            filaParaTabla[2] = novo.getProfesion();
            
            modeloTabla.addRow(filaParaTabla);
            limpiar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tableTrabajadores.getSelectedRow();
        
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this,"Selecciona un traballador da taboa");
        }else{
            listaTraballadores.remove(filaSeleccionada);
            modeloTabla.removeRow(filaSeleccionada);
            txtAreaTraballador.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTrabajadoresMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tableTrabajadores.getSelectedRow();
        
        if(filaSeleccionada != -1){
            
            Traballador traballadorSeleccionado = listaTraballadores.get(filaSeleccionada);
            
            if(evt.getClickCount() == 2){
                //Cogemos la provincia del seleccionado
                String provinciaSeleccionada = traballadorSeleccionado.getProvincia();
                //Contador para contar las personas de la misma provincia
                int contador=0;
                StringBuilder nombres = new StringBuilder();
                for(Traballador t : listaTraballadores){

                        if(t.getProvincia().equals(provinciaSeleccionada)){
                            contador++;
                            nombres.append(t.getNome())
                                    .append(" ")
                                    .append(t.getApelido1())
                                    .append(" ")
                                    .append(t.getApelido2())
                                    .append("\n");
                        }
                    
                }
                String mensaxe = "Traballadores de "+provinciaSeleccionada+ ": "+contador+"\n"+nombres;
                JOptionPane.showMessageDialog(this,mensaxe);
                
            }
             String detalles = "DATOS DO TRABALLADOR:\n"
                    + "DNI: " + traballadorSeleccionado.getDni() + "\n"
                    + "NOME: " + traballadorSeleccionado.getNome() + "\n"
                    + "APELIDO 1: " + traballadorSeleccionado.getApelido1() + "\n"
                    + "APELIDO 2: " + traballadorSeleccionado.getApelido2() + "\n"
                    + "PROVINCIA: " + traballadorSeleccionado.getProvincia() + "\n"
                    + "PROFESION: " + traballadorSeleccionado.getProfesion();
             txtAreaTraballador.setText(detalles);
        }
    }//GEN-LAST:event_tableTrabajadoresMouseClicked

    private void buttonPecharAplicaiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPecharAplicaiconActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonPecharAplicaiconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEliminarProfesion;
    private javax.swing.JButton buttonEliminarProvincia;
    private javax.swing.JButton buttonEngadirProfesion;
    private javax.swing.JButton buttonEngadirProvincia;
    private javax.swing.JButton buttonPecharAplicaicon;
    private javax.swing.JComboBox<String> comboProvincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listProfesion;
    private javax.swing.JTable tableTrabajadores;
    private javax.swing.JTextField txtApelido1;
    private javax.swing.JTextField txtApelido2;
    private javax.swing.JTextArea txtAreaTraballador;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProfesion;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables

public void limpiar(){
    txtDni.setText("");
    txtNome.setText("");
    txtApelido1.setText("");
    txtApelido2.setText("");
     comboProvincia.setSelectedIndex(-1);
     listProfesion.clearSelection();
}
}
