
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Carlos Maroño Ovies
 */
public class Formulario extends javax.swing.JPanel {
    private List<EventoListener> miListener= new ArrayList<>();
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        txtOtra.setEnabled(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radioHombre = new javax.swing.JRadioButton();
        radioMujer = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        boxA = new javax.swing.JCheckBox();
        boxB = new javax.swing.JCheckBox();
        boxC = new javax.swing.JCheckBox();
        boxD = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        radioNinguna = new javax.swing.JRadioButton();
        radioESO = new javax.swing.JRadioButton();
        radioBachillerato = new javax.swing.JRadioButton();
        radioFP = new javax.swing.JRadioButton();
        radioUniversidad = new javax.swing.JRadioButton();
        radioOtra = new javax.swing.JRadioButton();
        txtOtra = new javax.swing.JTextField();
        buttomGuardar = new javax.swing.JButton();

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido 1");

        jLabel4.setText("Apellido 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDNI)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido1)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        buttonGroup1.add(radioHombre);
        radioHombre.setSelected(true);
        radioHombre.setText("Hombre");

        buttonGroup1.add(radioMujer);
        radioMujer.setText("Mujer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioHombre)
                    .addComponent(radioMujer))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(radioHombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMujer)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carnets", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        boxA.setText("A");

        boxB.setText("B");

        boxC.setText("C");

        boxD.setText("D");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxA)
                    .addComponent(boxB)
                    .addComponent(boxC)
                    .addComponent(boxD))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(boxA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titulacion maxima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        buttonGroup2.add(radioNinguna);
        radioNinguna.setSelected(true);
        radioNinguna.setText("Ninguna");
        radioNinguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNingunaActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioESO);
        radioESO.setText("ESO");
        radioESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioESOActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioBachillerato);
        radioBachillerato.setText("Bachillerato");
        radioBachillerato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBachilleratoActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioFP);
        radioFP.setText("FP");
        radioFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFPActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioUniversidad);
        radioUniversidad.setText("Universidad");
        radioUniversidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUniversidadActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioOtra);
        radioOtra.setText("Otra");
        radioOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOtraActionPerformed(evt);
            }
        });

        txtOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNinguna)
                    .addComponent(radioESO)
                    .addComponent(radioBachillerato)
                    .addComponent(radioFP)
                    .addComponent(radioUniversidad))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioOtra)
                .addGap(28, 28, 28)
                .addComponent(txtOtra, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioNinguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioESO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBachillerato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioFP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioUniversidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioOtra)
                    .addComponent(txtOtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        buttomGuardar.setText("Guardar");
        buttomGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(buttomGuardar)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(buttomGuardar)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttomGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomGuardarActionPerformed
        // TODO add your handling code here:
       if(txtDNI.getText().isBlank()){
           fallo("Complete el dni");
           return;
       }
        if(txtNombre.getText().isBlank()){
            fallo("Complete el nombre");
            return;
        }
        if(txtApellido1.getText().isBlank()){
            fallo("Complete el Apellido 1");
                    return;
        }
        if(txtApellido2.getText().isBlank()){
            fallo("Complete el Apellido 2");
            return;
        }
        String dni = txtDNI.getText();
        String nombre = txtNombre.getText();
        String apellido1 = txtApellido1.getText();
        String apellido2 = txtApellido2.getText();
        
        List<Character> lista = new ArrayList<>();
        boolean marcado=false;
        if(boxA.isSelected()){
            lista.add('A');
            marcado=true;
        }
        if(boxB.isSelected()){
            lista.add('B');
            marcado=true;
        }
        if(boxC.isSelected()){
            lista.add('C');
            marcado=true;
        }
        if(boxD.isSelected()){
            lista.add('D');
            marcado=true;
        }
        if(marcado==false){
            fallo("Marque un carnet");
            return;
        }
        String genero="";
        if(radioHombre.isSelected()){
            genero="Hombre";
        }else{
            genero="Mujer";
        }
        String estudios="";
        if(radioNinguna.isSelected()){
            estudios="Ninguna";
        }
        if(radioESO.isSelected()){
            estudios="ESO";
        }
        if(radioFP.isSelected()){
            estudios="FP";
        }
        if(radioBachillerato.isSelected()){
            estudios="Bachillerato";
        }
        if(radioOtra.isSelected()){
            
            if(txtOtra.getText().isBlank()){
                fallo("Complete el campo de Otra");
                return;
            }
            estudios= txtOtra.getText();
        }
        Datos dato = new Datos(dni, nombre,apellido1, apellido2, lista, genero, estudios);
        
        exito(dato);
    }//GEN-LAST:event_buttomGuardarActionPerformed

    private void txtOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtOtraActionPerformed

    private void radioOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOtraActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(true);
    }//GEN-LAST:event_radioOtraActionPerformed

    private void radioNingunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNingunaActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioNingunaActionPerformed

    private void radioESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioESOActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioESOActionPerformed

    private void radioBachilleratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBachilleratoActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioBachilleratoActionPerformed

    private void radioFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFPActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioFPActionPerformed

    private void radioUniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUniversidadActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioUniversidadActionPerformed
    
    public void addListener(EventoListener listener){
        miListener.add(listener);
    }
    
    public void borrarListener(EventoListener listener){
        miListener.remove(listener);
    }
    
    public void fallo(String error){
        FalloEvent fail = new FalloEvent(this,error );
        
        for(EventoListener l : miListener){
            l.fallido(fail);
        }
    }
    
    public void exito(Datos dato){
        ExitoEvent exito = new ExitoEvent(this, dato);
        for(EventoListener l : miListener){
            l.exitoso(exito);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxA;
    private javax.swing.JCheckBox boxB;
    private javax.swing.JCheckBox boxC;
    private javax.swing.JCheckBox boxD;
    private javax.swing.JButton buttomGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton radioBachillerato;
    private javax.swing.JRadioButton radioESO;
    private javax.swing.JRadioButton radioFP;
    private javax.swing.JRadioButton radioHombre;
    private javax.swing.JRadioButton radioMujer;
    private javax.swing.JRadioButton radioNinguna;
    private javax.swing.JRadioButton radioOtra;
    private javax.swing.JRadioButton radioUniversidad;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOtra;
    // End of variables declaration//GEN-END:variables

    
}
