
import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carlosmo
 */
public class Padre extends javax.swing.JFrame {
    
    DefaultListModel<Hija> modeloListaHijas; 
    List<Hija> listaTipoA ;
    List<Hija> listaTipoB ;
    List<Hija> listaTipoC ;
    int contadorIDs;
    int contadorHijas;
    final int limiteListas = 5;
    
    /**
     * Creates new form Padre
     */
    public Padre() {
        initComponents();
        this.modeloListaHijas = new DefaultListModel<>();
        this.contadorHijas=0;
        this.contadorIDs=0;
        this.listaTipoA= new ArrayList<>();
        this.listaTipoB= new ArrayList<>();
        this.listaTipoC= new ArrayList<>();
        this.listVentanas.setModel(modeloListaHijas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupMostrar = new javax.swing.ButtonGroup();
        groupOcultar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioMostrarA = new javax.swing.JRadioButton();
        radioMostrarB = new javax.swing.JRadioButton();
        radioMostarC = new javax.swing.JRadioButton();
        radioMostrarTodas = new javax.swing.JRadioButton();
        buttonMostrar = new javax.swing.JButton();
        buttonHijaA = new javax.swing.JButton();
        buttonHijaB = new javax.swing.JButton();
        buttonHijaC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radioOcultarA = new javax.swing.JRadioButton();
        radioOcultarB = new javax.swing.JRadioButton();
        radioOcultarC = new javax.swing.JRadioButton();
        radioOcultarTodas = new javax.swing.JRadioButton();
        buttonOcultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVentanas = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelCantidadHijas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        groupMostrar.add(radioMostrarA);
        radioMostrarA.setText("Tipo A");

        groupMostrar.add(radioMostrarB);
        radioMostrarB.setText("Tipo B");

        groupMostrar.add(radioMostarC);
        radioMostarC.setText("Tipo C");

        groupMostrar.add(radioMostrarTodas);
        radioMostrarTodas.setText("Todas");

        buttonMostrar.setText("Mostrar");
        buttonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioMostrarA)
                    .addComponent(radioMostrarB)
                    .addComponent(radioMostarC)
                    .addComponent(radioMostrarTodas)
                    .addComponent(buttonMostrar))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioMostrarA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMostrarB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMostarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMostrarTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonHijaA.setText("Hija A");
        buttonHijaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHijaAActionPerformed(evt);
            }
        });

        buttonHijaB.setText("Hija B");
        buttonHijaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHijaBActionPerformed(evt);
            }
        });

        buttonHijaC.setText("Hija C");
        buttonHijaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHijaCActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Ocultar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        groupOcultar.add(radioOcultarA);
        radioOcultarA.setText("Tipo A");

        groupOcultar.add(radioOcultarB);
        radioOcultarB.setText("Tipo B");

        groupOcultar.add(radioOcultarC);
        radioOcultarC.setText("Tipo C");

        groupOcultar.add(radioOcultarTodas);
        radioOcultarTodas.setText("Todas");

        buttonOcultar.setText("Ocultar");
        buttonOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOcultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioOcultarA)
                    .addComponent(radioOcultarB)
                    .addComponent(radioOcultarC)
                    .addComponent(radioOcultarTodas)
                    .addComponent(buttonOcultar))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioOcultarA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOcultarB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOcultarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOcultarTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOcultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Ventanas hijas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jScrollPane1.setViewportView(listVentanas);

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ocultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        labelCantidadHijas.setText("Numero de hijos actuales:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCantidadHijas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonHijaA)
                            .addComponent(buttonHijaB)
                            .addComponent(buttonHijaC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonHijaA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonHijaB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonHijaC))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(labelCantidadHijas)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHijaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHijaAActionPerformed
        // TODO add your handling code here:
        if(listaTipoA.size()< limiteListas){
            Hija hijaA = new Hija(this,false);
            hijaA.setLocationRelativeTo(null);
            hijaA.setVisible(true);
            //Contador para el numero de ventana
            this.contadorIDs++;
            int numeroVentana = this.contadorIDs;
            hijaA.setTitle("A-"+numeroVentana);
            hijaA.setLabelHija("VENTANA TIPO A");
            listaTipoA.add(hijaA);
            modeloListaHijas.addElement(hijaA);
            acualizarContador();
        }else{
            JOptionPane.showMessageDialog(this,"Limite de Hijas Tipo A alcanzado");
        }
        
        
    }//GEN-LAST:event_buttonHijaAActionPerformed

    private void buttonHijaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHijaBActionPerformed
        // TODO add your handling code here:
        if(listaTipoB.size() < limiteListas){
            Hija hijaB = new Hija(this, false);
            hijaB.setLocationRelativeTo(null);
            hijaB.setVisible(true);
            this.contadorIDs++;
            int numeroVentana = this.contadorIDs;
             hijaB.setTitle("B-"+numeroVentana);
             hijaB.setLabelHija("VENTANA TIPO B");
            listaTipoB.add(hijaB);
            modeloListaHijas.addElement(hijaB);
            acualizarContador();
        }else{
            JOptionPane.showMessageDialog(this,"Limite de Hijas Tipo B alcanzado");
        }
    }//GEN-LAST:event_buttonHijaBActionPerformed

    private void buttonHijaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHijaCActionPerformed
        // TODO add your handling code here:
        if(listaTipoC.size()< limiteListas){
            Hija hijaC = new Hija(this,false);
            hijaC.setLocationRelativeTo(null);
            hijaC.setVisible(true);
              this.contadorIDs++;
            int numeroVentana = this.contadorIDs;
             hijaC.setTitle("C-"+numeroVentana);
             hijaC.setLabelHija("VENTANA TIPO C");
            listaTipoC.add(hijaC);
            modeloListaHijas.addElement(hijaC);
            acualizarContador();
        }else{
            JOptionPane.showMessageDialog(this,"Limite de Hijas Tipo C alcanzado");
        }
    }//GEN-LAST:event_buttonHijaCActionPerformed

    private void buttonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarActionPerformed
        // TODO add your handling code here:
        boolean algunoSeleccionado = radioMostrarA.isSelected() ||
                                     radioMostrarB.isSelected() ||
                                     radioMostarC.isSelected() ||
                                     radioMostrarTodas.isSelected();
        if(!algunoSeleccionado){
            JOptionPane.showMessageDialog(this,"Seleccione un tipo para mostrar");
        }else{
            
            if(radioMostrarA.isSelected()){
                for(Hija a : listaTipoA){
                    a.setVisible(true);
                }
            }
            if(radioMostrarB.isSelected()){
                for(Hija b : listaTipoB){
                    b.setVisible(true);
                }
            }
            if(radioMostarC.isSelected()){
                for(Hija c : listaTipoC){
                    c.setVisible(true);
                }
            }
            if(radioMostrarTodas.isSelected()){
                  for(Hija a : listaTipoA){
                    a.setVisible(true);
                }
                   for(Hija b : listaTipoB){
                    b.setVisible(true);
                }
                   for(Hija c : listaTipoC){
                    c.setVisible(true);
                }
            }
            listVentanas.repaint();
        }
    }//GEN-LAST:event_buttonMostrarActionPerformed

    private void buttonOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOcultarActionPerformed
        // TODO add your handling code here:
        boolean algunoSeleccionado = radioOcultarA.isSelected() ||
                                     radioOcultarB.isSelected() ||
                                     radioOcultarC.isSelected() ||
                                     radioOcultarTodas.isSelected();
        
        if(!algunoSeleccionado){
            JOptionPane.showMessageDialog(this,"Seleccione un tipo para ocultar");
        }else{
            
            if(radioOcultarA.isSelected()){
                for(Hija a : listaTipoA){
                    a.setVisible(false);
                    
                }
            }
            if(radioOcultarB.isSelected()){
                for(Hija b : listaTipoB){
                    b.setVisible(false);
                }
            }
            if(radioOcultarC.isSelected()){
                for(Hija c : listaTipoC){
                    c.setVisible(false);
                }
            }
            if(radioOcultarTodas.isSelected()){
                 for(Hija a : listaTipoA){
                    a.setVisible(false);
                }
                  for(Hija b : listaTipoB){
                    b.setVisible(false);
                }
                  for(Hija c : listaTipoC){
                    c.setVisible(false);
                }
            }
            listVentanas.repaint();
        }
        
        
        
    }//GEN-LAST:event_buttonOcultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(modeloListaHijas.isEmpty()){
            JOptionPane.showMessageDialog(this,"La lista esta vacia");
            return;
        } 
        List<Hija> ventanasSeleccionadas = listVentanas.getSelectedValuesList();
        
        if(ventanasSeleccionadas.isEmpty()){
             JOptionPane.showMessageDialog(this,"Selecciona almenos una ventana");
            return;
        }else{
            for(Hija a : ventanasSeleccionadas){
                a.setVisible(true);
            }
            listVentanas.repaint();
        }
          
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(modeloListaHijas.isEmpty()){
            JOptionPane.showMessageDialog(this,"La lista esta vacia");
            return;
        }
        List<Hija> ventanasSeleccionadas = listVentanas.getSelectedValuesList();
        
        if(ventanasSeleccionadas.isEmpty()){
            JOptionPane.showMessageDialog(this,"Selecciona almenos una ventana");
            return;
        }else{
            for(Hija a : ventanasSeleccionadas){
                a.setVisible(false);
            }
            listVentanas.repaint();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(modeloListaHijas.isEmpty()){
             JOptionPane.showMessageDialog(this,"La lista esta vacia");
            return;
        }
        List<Hija> ventanasSeleccionadas = listVentanas.getSelectedValuesList();
        
        if(ventanasSeleccionadas.isEmpty()){
            JOptionPane.showMessageDialog(this,"Selecciona almenos una ventana");
        }else{
            for(Hija a : ventanasSeleccionadas){
                a.dispose();
                modeloListaHijas.removeElement(a);
                if(a.getTitle().startsWith("A")){
                    listaTipoA.remove(a);
                }else if(a.getTitle().startsWith("B")){
                    listaTipoB.remove(a);
                }else if(a.getTitle().startsWith("C")){
                    listaTipoC.remove(a);
                }
            }
            acualizarContador();
            listVentanas.repaint();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Padre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHijaA;
    private javax.swing.JButton buttonHijaB;
    private javax.swing.JButton buttonHijaC;
    private javax.swing.JButton buttonMostrar;
    private javax.swing.JButton buttonOcultar;
    private javax.swing.ButtonGroup groupMostrar;
    private javax.swing.ButtonGroup groupOcultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantidadHijas;
    private javax.swing.JList<Hija> listVentanas;
    private javax.swing.JRadioButton radioMostarC;
    private javax.swing.JRadioButton radioMostrarA;
    private javax.swing.JRadioButton radioMostrarB;
    private javax.swing.JRadioButton radioMostrarTodas;
    private javax.swing.JRadioButton radioOcultarA;
    private javax.swing.JRadioButton radioOcultarB;
    private javax.swing.JRadioButton radioOcultarC;
    private javax.swing.JRadioButton radioOcultarTodas;
    // End of variables declaration//GEN-END:variables

private void acualizarContador(){
    this.contadorHijas = listaTipoA.size()+ listaTipoB.size()+ listaTipoC.size();
    
    labelCantidadHijas.setText("Numero de hijos actuales: "+this.contadorHijas);
}
}
