/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.informesservidorlinux;

/**
 *
 * @author Carlos Maroño Ovies
 */
public class Informes extends javax.swing.JFrame {
    private static final String MI_NOMBRE = "Carlos Maroño Ovies";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Informes.class.getName());

    /**
     * Creates new form Informes
     */
    public Informes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttomInforme1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ejercicio 1: Listado general de todos los registros (Sin filtros).");

        buttomInforme1.setText("Informe 1");
        buttomInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomInforme1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ejercicio 7: Validación gráfica de mayoría de edad (Imágenes).");

        jButton1.setText("Informe 7");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Ejercicio 2: Listado ordenado y agrupado por categorías.");

        jLabel4.setText("Ejercicio 3: Informe filtrado por un parámetro específico.");

        jLabel5.setText("Ejercicio 4: Búsqueda individual de persona por DNI.");

        jLabel6.setText("Ejercicio 5: Listado con cálculo automático de meses vividos.");

        jLabel7.setText("Ejercicio 6: Búsqueda por letra inicial del segundo apellido.");

        jButton2.setText("Informe 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Informe 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Informe 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Informe 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Informe 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(buttomInforme1))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(buttomInforme1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    try {
        java.io.InputStream reportStream = getClass().getResourceAsStream("/informes/Ejercicio7.jrxml");
        
        if (reportStream == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encuentra /informes/Ejercicio7.jrxml");
            return;
        }

       
        java.net.URL urlOK = getClass().getResource("/imagenes/ok.png");
        java.net.URL urlKO = getClass().getResource("/imagenes/ko.png");

       
        if (urlOK == null || urlKO == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encuentran las imágenes en la carpeta /imagenes/");
            return;
        }

      
        java.util.Map<String, Object> parametros = new java.util.HashMap<>();
        parametros.put("miNombre", MI_NOMBRE);
        
       
        parametros.put("imagenOK", urlOK.toString());
        parametros.put("imagenKO", urlKO.toString());

       
        net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);
        net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parametros, Conexion.getConexion());

        if (print.getPages().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para mostrar.");
        } else {
            net.sf.jasperreports.view.JasperViewer.viewReport(print, false);
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttomInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomInforme1ActionPerformed

        // TODO add your handling code here:
    try {
    String reportPath = "C:\\Users\\Usuario\\JaspersoftWorkspace\\MyReports\\Ejercicio1.jrxml";

    java.util.Map<String, Object> parametros = new java.util.HashMap<>();
    parametros.put("miNombre", MI_NOMBRE);

    net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportPath);
    net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parametros, Conexion.getConexion());

    if (print.getPages().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para mostrar.");
    } else {
        net.sf.jasperreports.view.JasperViewer.viewReport(print, false);
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}    
        
        
    }//GEN-LAST:event_buttomInforme1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
       
        java.io.InputStream reportStream = getClass().getResourceAsStream("/informes/Ejercicio2.jrxml");

      
        if (reportStream == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encuentra el archivo /informes/Ejercicio2.jrxml dentro del proyecto.");
            return;
        }

      
        java.util.Map<String, Object> parametros = new java.util.HashMap<>();
        parametros.put("miNombre", MI_NOMBRE);

      
        net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);
        
 
        net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parametros, Conexion.getConexion());

        if (print.getPages().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para mostrar.");
        } else {
         
            net.sf.jasperreports.view.JasperViewer.viewReport(print, false);
        }

    } catch (Exception e) {
        e.printStackTrace(); 
        javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el informe 2: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            java.io.InputStream reportStream = getClass().getResourceAsStream("/informes/Ejercicio3.jrxml");

            if (reportStream == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encuentra el archivo /informes/Ejercicio3.jrxml");
                return;
            }

            java.util.Map<String, Object> parametros = new java.util.HashMap<>();
            parametros.put("miNombre", MI_NOMBRE);

            net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);
            net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parametros, Conexion.getConexion());

            if (print.getPages().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para mostrar.");
            } else {
                net.sf.jasperreports.view.JasperViewer.viewReport(print, false);
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String dni = javax.swing.JOptionPane.showInputDialog(this, "Introduce el DNI a buscar:");

        if (dni != null && !dni.isEmpty()) {
            try {
                java.io.InputStream reportStream = getClass().getResourceAsStream("/informes/Ejercicio4.jrxml");

                if (reportStream == null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No se encuentra el archivo /informes/Ejercicio4.jrxml");
                    return;
                }

                java.util.Map<String, Object> parametros = new java.util.HashMap<>();
                parametros.put("miNombre", MI_NOMBRE);
                parametros.put("dni", dni);

                net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);
                net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parametros, Conexion.getConexion());

                if (print.getPages().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para mostrar.");
                } else {
                    net.sf.jasperreports.view.JasperViewer.viewReport(print, false);
                }

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     try {
            String minStr = javax.swing.JOptionPane.showInputDialog(this, "Introduce la edad MÍNIMA:");
            if (minStr == null) return;

            String maxStr = javax.swing.JOptionPane.showInputDialog(this, "Introduce la edad MÁXIMA:");
            if (maxStr == null) return;

            if (!minStr.isEmpty() && !maxStr.isEmpty()) {
                int edadMin = Integer.parseInt(minStr);
                int edadMax = Integer.parseInt(maxStr);

                java.io.InputStream reportStream = getClass().getResourceAsStream("/informes/Ejercicio5.jrxml");

                if (reportStream == null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No se encuentra el archivo /informes/Ejercicio5.jrxml");
                    return;
                }

                java.util.Map<String, Object> parametros = new java.util.HashMap<>();
                parametros.put("miNombre", MI_NOMBRE);
                parametros.put("edadMinima", edadMin);
                parametros.put("edadMaxima", edadMax);

                net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);
                net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parametros, Conexion.getConexion());

                if (print.getPages().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para el rango seleccionado.");
                } else {
                    net.sf.jasperreports.view.JasperViewer.viewReport(print, false);
                }
            }
        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, introduce solo números válidos.");
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    String letra = javax.swing.JOptionPane.showInputDialog(this, "Introduce la inicial del segundo apellido:");

        if (letra != null && !letra.isEmpty()) {
            try {
                java.io.InputStream reportStream = getClass().getResourceAsStream("/informes/Ejercicio6.jrxml");

                if (reportStream == null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No se encuentra el archivo /informes/Ejercicio6.jrxml");
                    return;
                }

                java.util.Map<String, Object> parametros = new java.util.HashMap<>();
                parametros.put("miNombre", MI_NOMBRE);
                parametros.put("letra", letra);

                net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);
                net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parametros, Conexion.getConexion());

                if (print.getPages().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para esa letra.");
                } else {
                    net.sf.jasperreports.view.JasperViewer.viewReport(print, false);
                }

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Informes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttomInforme1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
