
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carlos Maroño Ovies
 */
public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());
    private List<Persona> listaPersonas;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.listaPersonas = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgTitulacion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radioHombre = new javax.swing.JRadioButton();
        radioMujer = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        checkA = new javax.swing.JCheckBox();
        checkB = new javax.swing.JCheckBox();
        checkC = new javax.swing.JCheckBox();
        checkD = new javax.swing.JCheckBox();
        checkE = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        radioNinguna = new javax.swing.JRadioButton();
        radioBachillerato = new javax.swing.JRadioButton();
        radioFp = new javax.swing.JRadioButton();
        radioEso = new javax.swing.JRadioButton();
        radioUniversidad = new javax.swing.JRadioButton();
        radioOtra = new javax.swing.JRadioButton();
        txtOtra = new javax.swing.JTextField();
        butonGuardar = new javax.swing.JButton();
        butonBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido 1");

        jLabel4.setText("Apellido 2");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(170, 170, 170), new java.awt.Color(170, 170, 170)), "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        bgSexo.add(radioHombre);
        radioHombre.setSelected(true);
        radioHombre.setText("Hombre");

        bgSexo.add(radioMujer);
        radioMujer.setText("Mujer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioMujer)
                    .addComponent(radioHombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(radioHombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMujer)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(216, 215, 215), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Permiso conducir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        checkA.setText("A");

        checkB.setText("B");

        checkC.setText("C");

        checkD.setText("D");
        checkD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDActionPerformed(evt);
            }
        });

        checkE.setText("E");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkE)
                    .addComponent(checkB)
                    .addComponent(checkA)
                    .addComponent(checkC)
                    .addComponent(checkD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(checkA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkB)
                .addGap(10, 10, 10)
                .addComponent(checkC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(214, 214, 214), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Titulación máxima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        bgTitulacion.add(radioNinguna);
        radioNinguna.setSelected(true);
        radioNinguna.setText("Ninguna");
        radioNinguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNingunaActionPerformed(evt);
            }
        });

        bgTitulacion.add(radioBachillerato);
        radioBachillerato.setText("Bachillerato");
        radioBachillerato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBachilleratoActionPerformed(evt);
            }
        });

        bgTitulacion.add(radioFp);
        radioFp.setText("FP");
        radioFp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFpActionPerformed(evt);
            }
        });

        bgTitulacion.add(radioEso);
        radioEso.setText("ESO");
        radioEso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEsoActionPerformed(evt);
            }
        });

        bgTitulacion.add(radioUniversidad);
        radioUniversidad.setText("Universitaria");
        radioUniversidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUniversidadActionPerformed(evt);
            }
        });

        bgTitulacion.add(radioOtra);
        radioOtra.setText("Otra");
        radioOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOtraActionPerformed(evt);
            }
        });

        txtOtra.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radioOtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(txtOtra, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radioUniversidad)
                    .addComponent(radioEso)
                    .addComponent(radioFp)
                    .addComponent(radioBachillerato)
                    .addComponent(radioNinguna))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioNinguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioEso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBachillerato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioFp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioUniversidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioOtra)
                    .addComponent(txtOtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        butonGuardar.setText("Guardar");
        butonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGuardarActionPerformed(evt);
            }
        });

        butonBuscar.setText("Buscar");
        butonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApellido1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApellido2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre)
                                            .addComponent(txtDni))))
                                .addGap(18, 18, 18))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonGuardar)
                    .addComponent(butonBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void checkDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDActionPerformed

    private void butonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGuardarActionPerformed
        
        //Lista para guardar los permisos
        List<Character> permisosConducir = new ArrayList<>();
        
        //Comprobar si hay algun permiso seleccionado
        boolean algunoSeleccionado = checkA.isSelected() ||
                                     checkB.isSelected() ||
                                     checkC.isSelected() ||
                                     checkD.isSelected() ||
                                     checkE.isSelected();
        //Titulacion seleccionada
        String tituloSeleccionado ="";
        
        //Genero
        String genero="";
        
        if(txtDni.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Complete el DNI");
        }
       else if(txtNombre.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Completa el Nombre");
        }
       else if(txtApellido1.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Completa el Apellido 1");
        }
       else if(txtApellido2.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Completa el Apellido 2");
        }
     
       else if(!algunoSeleccionado){
            JOptionPane.showMessageDialog(this,"Debes seleccionar almenos un permiso de conducir");
       }
       else if(radioOtra.isSelected() && txtOtra.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Si selecciona 'Otra', debes especificar la titulacion");
       }
       
       else{
           if(radioNinguna.isSelected()){
               tituloSeleccionado = "Ninguna";
           }
           else if(radioEso.isSelected()){
               tituloSeleccionado = "ESO";
           }
           else if(radioBachillerato.isSelected()){
               tituloSeleccionado ="Bachillerato";
           }
           else if(radioFp.isSelected()){
               tituloSeleccionado = "FP";
           }
           else if(radioUniversidad.isSelected()){
               tituloSeleccionado = "Universitaria";
           }
           else if(radioOtra.isSelected()){
               tituloSeleccionado = txtOtra.getText();
           }
           if(checkA.isSelected()){
               permisosConducir.add('A'); 
           }
           if(checkB.isSelected()){
               permisosConducir.add('B');
           }
           if(checkC.isSelected()){
               permisosConducir.add('C');
           }
           if(checkD.isSelected()){
               permisosConducir.add('D');
           }
           if(checkE.isSelected()){
               permisosConducir.add('E');
           }
           if(radioHombre.isSelected()){
               genero = "Hombre";
           }else{
               genero = "Mujer";
           }
           
           //Comprobacion dni
           String dniComprobar = txtDni.getText();
           boolean repetido = false;
           for(Persona p : listaPersonas){
               if(p.getDni().equalsIgnoreCase(dniComprobar)){
                   repetido =true;
                   break;
               }
           }
           if(repetido){
               JOptionPane.showMessageDialog(this,"Ya existe una persona con ese DNI en el registro");
           }
           else{
                 Persona nuevaPersona = new Persona(txtDni.getText(), txtNombre.getText(), txtApellido1.getText(),
                                           txtApellido2.getText(),genero , permisosConducir, tituloSeleccionado);
                    this.listaPersonas.add(nuevaPersona);
                  
                    //Mensaje para confirmar que esta correcto el añadido
                    JOptionPane.showMessageDialog(this, "Persona guardada con éxito.");
                    //Limpiamos formulario al añadir la persona
                    limpiarFormulario();
           }
           
           
      
       }
       
    }//GEN-LAST:event_butonGuardarActionPerformed

    private void radioNingunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNingunaActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioNingunaActionPerformed

    private void radioEsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEsoActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioEsoActionPerformed

    private void radioBachilleratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBachilleratoActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioBachilleratoActionPerformed

    private void radioFpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFpActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioFpActionPerformed

    private void radioUniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUniversidadActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(false);
        txtOtra.setText("");
    }//GEN-LAST:event_radioUniversidadActionPerformed

    private void radioOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOtraActionPerformed
        // TODO add your handling code here:
        txtOtra.setEnabled(true);
       
    }//GEN-LAST:event_radioOtraActionPerformed

    private void butonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonBuscarActionPerformed
        
        
        if(txtBuscar.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Debe introducir un dni");
        }else{
            //Buscamos a la persona
            String dniBuscar = txtBuscar.getText();
            boolean encontrada=false;
            Persona buscada = null;
            for(Persona p : listaPersonas){
                if(p.getDni().equalsIgnoreCase(dniBuscar)){
                    encontrada =true;
                    buscada = p;
                    break;
                }
            }
            //Si la encontramos empezamos a rellenar el formulario
            if(encontrada){
                //Limpiamos
                limpiarFormulario();
                //Cubrimos campos
                txtDni.setText(buscada.getDni());
                txtNombre.setText(buscada.getNombre());
                txtApellido1.setText(buscada.getApellido1());
                txtApellido2.setText(buscada.getApellido2());
                //Generos
                if(buscada.getGenero().equals("Hombre")){
                    radioHombre.setSelected(true);
                }else{
                    radioMujer.setSelected(true);
                }
                //Permisos
                for(Character permiso : buscada.getPermiso()){
                    
                    if(permiso == 'A'){
                        checkA.setSelected(true);
                    }
                    if(permiso == 'B'){
                        checkB.setSelected(true);
                    }
                    if(permiso == 'C'){
                        checkC.setSelected(true);
                    }
                    if(permiso == 'D'){
                        checkD.setSelected(true);
                    }
                    if(permiso == 'E'){
                        checkE.setSelected(true);
                    }
                }
                //Estudios
                String estudios = buscada.getTitulacion();
                
                if(estudios.equals("ESO")){
                    radioEso.setSelected(true);
                } 
                else if(estudios.equals("Bachillerato")){
                    radioBachillerato.setSelected(true);
                }
                else if(estudios.equals("FP")){
                    radioFp.setSelected(true);
                }
                else if(estudios.equals("Universitaria")){
                    radioUniversidad.setSelected(true);
                }
                else if(estudios.equals("Ninguna")){
                    radioNinguna.setSelected(true);
                }else{
                    radioOtra.setSelected(true);
                    txtOtra.setEnabled(true);
                    txtOtra.setText(buscada.getTitulacion());
                }
                
                
            } else{
                JOptionPane.showMessageDialog(this, "No se encontró ninguna persona con ese DNI.");
            }
        }
    }//GEN-LAST:event_butonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.ButtonGroup bgTitulacion;
    private javax.swing.JButton butonBuscar;
    private javax.swing.JButton butonGuardar;
    private javax.swing.JCheckBox checkA;
    private javax.swing.JCheckBox checkB;
    private javax.swing.JCheckBox checkC;
    private javax.swing.JCheckBox checkD;
    private javax.swing.JCheckBox checkE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton radioBachillerato;
    private javax.swing.JRadioButton radioEso;
    private javax.swing.JRadioButton radioFp;
    private javax.swing.JRadioButton radioHombre;
    private javax.swing.JRadioButton radioMujer;
    private javax.swing.JRadioButton radioNinguna;
    private javax.swing.JRadioButton radioOtra;
    private javax.swing.JRadioButton radioUniversidad;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOtra;
    // End of variables declaration//GEN-END:variables

private void limpiarFormulario(){
   
    txtDni.setText("");
    txtNombre.setText("");
    txtApellido1.setText("");
    txtApellido2.setText("");

    checkA.setSelected(false);
    checkB.setSelected(false);
    checkC.setSelected(false);
    checkD.setSelected(false);
    checkE.setSelected(false);

    radioHombre.setSelected(true); 
    radioNinguna.setSelected(true); 
    txtOtra.setText("");
    txtOtra.setEnabled(false);
}

}
